(function(){
  if(!location.pathname.endsWith('/agents/crypto.html'))return;
  const originalFetch=window.fetch.bind(window);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=v=>{v=Number(v);if(!Number.isFinite(v))return'—';if(Math.abs(v)>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(Math.abs(v)>=1e6)return'$'+(v/1e6).toFixed(1)+'M';if(Math.abs(v)>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toLocaleString('tr-TR',{maximumFractionDigits:2})};
  const num=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('tr-TR',{maximumFractionDigits:2});
  const pct=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(2)+'%';
  function section(out,prefix){return [...out.querySelectorAll('.ci-section')].find(s=>(s.querySelector('h3')?.textContent||'').startsWith(prefix))}
  function renderAllocation(r){const a=r.token_allocation||{};if(!a.available)return'';const labels=[...new Set([...(a.current||[]).map(x=>x.label),...(a.final||[]).map(x=>x.label)])];const cur=Object.fromEntries((a.current||[]).map(x=>[x.label,x.pct])),fin=Object.fromEntries((a.final||[]).map(x=>[x.label,x.pct]));const title=(a.current||[]).length?'Token Dağılımı · Şu An vs Nihai':'Token Dağılımı';let h=`<div class="ci-section"><h3>${title}</h3><div style="overflow:auto"><table class="ci-table"><tr><th>Kategori</th>${(a.current||[]).length?'<th>Şu an</th>':''}<th>Nihai</th></tr>${labels.map(l=>`<tr><td>${esc(l)}</td>${(a.current||[]).length?`<td>${pct(cur[l])}</td>`:''}<td>${pct(fin[l])}</td></tr>`).join('')}</table></div>`;if((a.release_mechanisms||[]).length)h+=`<div class="ci-section"><h3>Vesting / Release Mekanizması</h3><div style="overflow:auto"><table class="ci-table"><tr><th>Kategori</th><th>Pay</th><th>Lockup / Mekanizma</th><th>Cliff</th><th>Cliff'te Açılan</th></tr>${a.release_mechanisms.map(x=>`<tr><td>${esc(x.label||'—')}</td><td>${pct(x.allocation_pct)}</td><td>${esc(x.mechanism||x.lockup||'—')}</td><td>${esc(x.cliff||'—')}</td><td>${esc(x.unlock_at_cliff||'—')}</td></tr>`).join('')}</table></div></div>`;return h+'</div>'}
  function renderUnlock(r){const u=r.unlock_schedule||{};if(!u.available)return'<div class="ci-warn">Kamuya açık doğrulanmış unlock takvimi bulunamadı.</div>';const n=u.next_event||{},m=u.next_major_cliff||{};let h=`<div class="ci-grid"><div class="ci-box"><div class="ci-label">Unlocked Supply</div><div class="ci-value">${pct(u.unlocked_pct)}</div>${u.unlocked_tokens!=null?`<div class="ci-muted">${num(u.unlocked_tokens)} token</div>`:''}</div><div class="ci-box"><div class="ci-label">Sıradaki Scheduled Release</div><div class="ci-value">${esc(n.date||'—')}</div><div class="ci-muted">${n.tokens!=null?num(n.tokens)+' token':''}${n.pct_float!=null?' · float '+pct(n.pct_float):''}</div></div><div class="ci-box"><div class="ci-label">Sıradaki Büyük Cliff</div><div class="ci-value">${esc(m.date||'—')}</div><div class="ci-muted">${m.pct_total!=null?'Total '+pct(m.pct_total):''}${m.pct_mcap!=null?' · MCap '+pct(m.pct_mcap):''}</div></div><div class="ci-box"><div class="ci-label">Sıradaki Alıcı</div><div class="ci-value">${esc(n.category||'—')}</div></div></div>`;if((u.events||[]).length)h+=`<div style="overflow:auto"><table class="ci-table"><tr><th>Tarih</th><th>Tip</th><th>Kategori</th><th>Token</th><th>% Total</th><th>% Float</th><th>% MCap</th></tr>${u.events.map(e=>`<tr><td>${esc(e.date||'—')}</td><td>${esc(e.type||'—')}</td><td>${esc(e.category||'—')}</td><td>${num(e.tokens)}</td><td>${pct(e.pct_total)}</td><td>${pct(e.pct_float)}</td><td>${pct(e.pct_mcap)}</td></tr>`).join('')}</table></div>`;return h}
  function renderInvestors(r){const f=r.funding||{},ii=r.investors||{};if(!f.available)return'<div class="ci-warn">Kamuya açık funding/backer verisi doğrulanamadı.</div>';const prof=Object.fromEntries((ii.items||[]).map(x=>[String(x.name||'').toLowerCase(),x]));let h=`<div class="ci-grid"><div class="ci-box"><div class="ci-label">Toplam Raise</div><div class="ci-value">${money(f.total_raised_usd)}</div></div><div class="ci-box"><div class="ci-label">Private Round Toplamı</div><div class="ci-value">${money(f.private_rounds_usd)}</div></div><div class="ci-box"><div class="ci-label">Doğrulanmış Yatırımcı</div><div class="ci-value">${(f.investors||[]).length}</div></div><div class="ci-box"><div class="ci-label">Research Güveni</div><div class="ci-value">${esc((r.evidence||{}).confidence||'—')}</div></div></div>`;if((f.rounds||[]).length)h+=`<div style="overflow:auto"><table class="ci-table"><tr><th>Tarih</th><th>Tur</th><th>Tutar</th><th>Yatırımcılar</th></tr>${f.rounds.map(x=>`<tr><td>${esc(x.date||'—')}</td><td>${esc(x.round||'—')}</td><td>${money(x.amount_usd)}</td><td>${esc((x.investors||[]).join(', ')||'—')}</td></tr>`).join('')}</table></div>`;if((f.investors||[]).length)h+=`<div class="ci-section"><h3>Yatırımcı Kalitesi / Diğer Yatırımları</h3><div style="overflow:auto"><table class="ci-table"><tr><th>Yatırımcı</th><th>Profil</th><th>Diğer yatırımlar</th><th>Neden önemli?</th></tr>${f.investors.map(n=>{const p=prof[String(n).toLowerCase()]||{};return `<tr><td><b>${esc(n)}</b></td><td>${esc(p.importance||'PUBLIC-RESEARCH')}${p.total_investments!=null?` · ${p.total_investments} yatırım`:''}</td><td>${esc((p.other_investments||[]).join(', ')||'—')}</td><td>${esc(p.why_it_matters||'Doğrulanmış yatırım turunda yer alıyor.')}</td></tr>`}).join('')}</table></div></div>`;return h}
  function patch(d){const out=document.getElementById('coinIntelResult');if(!out)return;const r=d.public_research||{};const unlock=section(out,'Unlock Risk'),invest=section(out,'Backers / Investors');if(unlock)unlock.innerHTML=`<h3>Unlock Risk</h3>${renderUnlock(r)}${renderAllocation(r)}`;if(invest)invest.innerHTML=`<h3>Backers / Investors · Neden Önemli?</h3>${renderInvestors(r)}`}
  window.fetch=async function(input,init){const response=await originalFetch(input,init);try{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.includes('/api/public/coin-intelligence'))response.clone().json().then(d=>{if(d&&!d.error)setTimeout(()=>patch(d),100)}).catch(()=>{})}catch(e){}return response};
})();
