(function(){
  if(!location.pathname.endsWith('/agents/crypto.html'))return;
  const API='https://project-alpha-terminal.onrender.com/api/public/coin-intelligence';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=v=>{v=Number(v);if(!Number.isFinite(v))return'—';if(Math.abs(v)>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(Math.abs(v)>=1e6)return'$'+(v/1e6).toFixed(1)+'M';if(Math.abs(v)>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toLocaleString('tr-TR',{maximumFractionDigits:2})};
  const num=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('tr-TR',{maximumFractionDigits:2});
  const pct=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(1)+'%';
  const riskClass=v=>v==='HIGH'?'negative':v==='LOW'?'positive':'';
  const st=document.createElement('style');st.textContent=`
    .coin-intel-search{display:flex;gap:8px;margin:10px 0 14px}.coin-intel-search input{flex:1;min-width:0;background:#071008;border:1px solid var(--green-dim,#175c3a);color:var(--text,#d7ffe6);border-radius:8px;padding:11px 12px;font:600 12px 'IBM Plex Mono',monospace;text-transform:uppercase}.coin-intel-search button{border:1px solid var(--green,#39ff88);background:rgba(57,255,136,.09);color:var(--green,#39ff88);border-radius:8px;padding:10px 15px;font:700 11px 'IBM Plex Mono',monospace;cursor:pointer}.ci-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:10px 0}.ci-box{border:1px solid rgba(57,255,136,.13);border-radius:9px;padding:10px;background:rgba(0,0,0,.12)}.ci-label{font-size:8px;color:var(--muted);text-transform:uppercase;letter-spacing:.07em}.ci-value{font-size:15px;font-weight:800;margin-top:5px}.ci-section{border-top:1px solid rgba(57,255,136,.11);padding-top:12px;margin-top:12px}.ci-section h3{font-size:11px;color:#dfffea;margin:0 0 8px}.ci-text{font-size:10px;line-height:1.55;color:#bcd7c7}.ci-tags{display:flex;gap:5px;flex-wrap:wrap}.ci-tag{font-size:8px;border:1px solid rgba(57,255,136,.2);border-radius:999px;padding:4px 7px;color:#9fceb2}.ci-table{width:100%;border-collapse:collapse;font-size:9px}.ci-table th,.ci-table td{padding:7px 5px;border-bottom:1px solid rgba(57,255,136,.09);text-align:left;vertical-align:top}.ci-muted{font-size:9px;color:var(--muted);line-height:1.5}.ci-warn{border:1px solid rgba(255,207,92,.25);background:rgba(255,207,92,.04);padding:9px;border-radius:8px;color:#ffcf5c;font-size:9px}.ci-loading{padding:18px;color:var(--muted);font-size:10px}.ci-score{font-weight:800}.ci-score.good{color:var(--green)}.ci-score.bad{color:var(--red,#ff5c5c)}@media(max-width:800px){.ci-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.coin-intel-search{flex-direction:column}}
  `;document.head.appendChild(st);

  function investorsBlock(x){
    const ii=x.investor_intelligence||{};
    if(!ii.available)return `<div class="ci-warn">Yatırımcı/round verisi bu analizde doğrulanamadı. Sistem yatırımcı ismi tahmin etmiyor; doğrulanmış veri katmanı aktif olduğunda otomatik dolar.</div>`;
    const rows=(ii.investors||[]).map(i=>`<tr><td><b>${esc(i.name)}</b><div class="ci-muted">${esc(i.importance)}</div></td><td>${i.portfolio_count??0}</td><td>${esc((i.other_investments||[]).join(', ')||'—')}</td><td>${esc(i.why_it_matters||'—')}</td></tr>`).join('');
    return `<div style="overflow:auto"><table class="ci-table"><tr><th>Yatırımcı</th><th>Diğer yatırım sayısı</th><th>Başka nerelere yatırım yaptı?</th><th>Neden önemli?</th></tr>${rows||'<tr><td colspan="4">—</td></tr>'}</table></div>`;
  }
  function unlockBlock(x){const u=x.unlock_risk||{};if(!u.available)return'<div class="ci-warn">Doğrulanmış unlock takvimi bu coin için şu anda mevcut değil; unlock riski tahmin edilmiyor.</div>';const w=u.unlock_pct_circ||{};return `<div class="ci-grid"><div class="ci-box"><div class="ci-label">7g Unlock / Float</div><div class="ci-value">${pct(w['7d'])}</div></div><div class="ci-box"><div class="ci-label">30g</div><div class="ci-value">${pct(w['30d'])}</div></div><div class="ci-box"><div class="ci-label">90g</div><div class="ci-value">${pct(w['90d'])}</div></div><div class="ci-box"><div class="ci-label">1Y</div><div class="ci-value">${pct(w['365d'])}</div></div></div>`}
  function render(x){
    const c=x.coin||{},t=x.tokenomics||{},a=x.actual_adoption||{},r=x.revenue||{},as=x.assessment||{},tech=x.technology_product||{},n=x.narrative||{},sm=x.smart_money||{};
    return `<div class="intel-head"><div><h2>${esc(c.symbol||'COIN')} Intelligence · Fundamental + On-chain</h2><div class="intel-meta">${esc(c.name||'')} · Rank #${c.rank??'—'} · Fiyat ${money(c.price_usd)}</div></div><span class="tag-method">EVIDENCE-FIRST</span></div>
    <div class="ci-grid"><div class="ci-box"><div class="ci-label">Market Cap</div><div class="ci-value">${money(c.market_cap_usd)}</div></div><div class="ci-box"><div class="ci-label">FDV</div><div class="ci-value">${money(c.fdv_usd)}</div></div><div class="ci-box"><div class="ci-label">Long-term Potential</div><div class="ci-value ci-score ${Number(as.long_term_potential_score)>=60?'good':Number(as.long_term_potential_score)<40?'bad':''}">${as.long_term_potential_score??'—'}/100</div></div><div class="ci-box"><div class="ci-label">Short-term Supply Risk</div><div class="ci-value ${riskClass(as.short_term_supply_risk)}">${esc(as.short_term_supply_risk||'UNKNOWN')}</div></div></div>
    <div class="ci-section"><h3>Technology / Product</h3><div class="ci-text">${esc(tech.summary||'Ürün açıklaması doğrulanamadı.')}</div><div class="ci-muted">Public repo bağlantısı: ${tech.github_repos??0} · Ürün sitesi: ${tech.homepage?'var':'yok / doğrulanmadı'}</div></div>
    <div class="ci-section"><h3>Narrative</h3><div class="ci-tags">${(n.categories||[]).map(v=>`<span class="ci-tag">${esc(v)}</span>`).join('')||'<span class="ci-muted">—</span>'}</div></div>
    <div class="ci-section"><h3>Actual Adoption + Revenue</h3><div class="ci-grid"><div class="ci-box"><div class="ci-label">TVL / Adoption proxy</div><div class="ci-value">${money(a.tvl_usd)}</div><div class="ci-muted">Score ${a.score??'—'}/100</div></div><div class="ci-box"><div class="ci-label">Revenue 24h</div><div class="ci-value">${money(r['24h_usd'])}</div></div><div class="ci-box"><div class="ci-label">Revenue 30g</div><div class="ci-value">${money(r['30d_usd'])}</div><div class="ci-muted">Score ${r.score??'—'}/100</div></div><div class="ci-box"><div class="ci-label">Developer signal</div><div class="ci-value">${num(a.developer_score)}</div></div></div></div>
    <div class="ci-section"><h3>Token Utility</h3><div class="ci-text">${esc((x.token_utility||{}).note||'—')}</div></div>
    <div class="ci-section"><h3>Tokenomics</h3><div class="ci-grid"><div class="ci-box"><div class="ci-label">Circulating</div><div class="ci-value">${num(t.circulating_supply)}</div></div><div class="ci-box"><div class="ci-label">Total Supply</div><div class="ci-value">${num(t.total_supply)}</div></div><div class="ci-box"><div class="ci-label">Float %</div><div class="ci-value">${pct(t.float_pct)}</div></div><div class="ci-box"><div class="ci-label">FDV / MCap</div><div class="ci-value">${pct(t.fdv_to_mcap_pct)}</div></div></div></div>
    <div class="ci-section"><h3>Unlock Risk</h3>${unlockBlock(x)}</div>
    <div class="ci-section"><h3>Backers / Investors · Neden Önemli?</h3>${investorsBlock(x)}</div>
    <div class="ci-section"><h3>VC / Team Wallets · Exchange Inflows · Whale Activity</h3>${sm.available?'<div class="ci-text">Etiketli cüzdan aktivitesi mevcut.</div>':`<div class="ci-warn">${esc(sm.note||'Etiketli smart-money verisi mevcut değil.')}</div>`}</div>
    <div class="ci-section"><h3>What Would Change My View?</h3><div class="ci-text"><b class="positive">Bull:</b> ${esc((as.what_changes_view||{}).bull||'—')}<br><b class="negative">Bear:</b> ${esc((as.what_changes_view||{}).bear||'—')}</div></div>
    <div class="ci-muted" style="margin-top:12px">Veri tamlığı: ${esc(as.data_completeness||'—')}. Yatırımcı, unlock veya cüzdan etiketlemesi doğrulanamıyorsa sistem tahmin üretmez.</div>`;
  }

  function mount(){
    const content=document.getElementById('content');if(!content||document.getElementById('coinIntelligenceCard'))return;
    const card=document.createElement('div');card.className='card';card.id='coinIntelligenceCard';
    card.innerHTML=`<h2>Coin Intelligence · Fundamental + On-chain</h2><div class="note">Coin sembolü veya adını ara. Technology, narrative, adoption, revenue, tokenomics, unlock, yatırımcı kalitesi ve smart-money katmanlarını tek raporda toplar.</div><div class="coin-intel-search"><input id="coinIntelInput" maxlength="40" placeholder="XPL, HYPE, AAVE..." autocomplete="off"><button id="coinIntelBtn">ANALİZ ET</button></div><div id="coinIntelResult" class="ci-muted">Bir coin aratarak başlayabilirsin.</div>`;
    content.insertBefore(card,content.firstChild);
    const input=card.querySelector('#coinIntelInput'),btn=card.querySelector('#coinIntelBtn'),out=card.querySelector('#coinIntelResult');
    async function go(){const q=input.value.trim();if(!q)return;btn.disabled=true;btn.textContent='ANALİZ...';out.innerHTML='<div class="ci-loading">Fundamental, tokenomics ve yatırımcı verileri taranıyor…</div>';try{const r=await fetch(API+'?q='+encodeURIComponent(q),{cache:'no-store'});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Analiz alınamadı');out.innerHTML=render(d)}catch(e){out.innerHTML='<div class="error-box">⚠️ '+esc(e.message)+'</div>'}finally{btn.disabled=false;btn.textContent='ANALİZ ET'}}
    btn.addEventListener('click',go);input.addEventListener('keydown',e=>{if(e.key==='Enter')go()});
  }
  setTimeout(mount,500);
})();
