(function(){
  if(!location.pathname.endsWith('/agents/crypto.html'))return;
  const originalFetch=window.fetch.bind(window);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=v=>{v=Number(v);if(!Number.isFinite(v))return'—';if(Math.abs(v)>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(Math.abs(v)>=1e6)return'$'+(v/1e6).toFixed(1)+'M';if(Math.abs(v)>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toLocaleString('tr-TR',{maximumFractionDigits:2})};
  const num=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('tr-TR',{maximumFractionDigits:2});
  const pct=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(2)+'%';
  function section(out,prefix){return [...out.querySelectorAll('.ci-section')].find(s=>(s.querySelector('h3')?.textContent||'').startsWith(prefix))}
  function renderAllocation(r){const a=r.token_allocation||{};if(!a.available)return'';const labels=[...new Set([...(a.current||[]).map(x=>x.label),...(a.final||[]).map(x=>x.label)])];const cur=Object.fromEntries((a.current||[]).map(x=>[x.label,x.pct])),fin=Object.fromEntries((a.final||[]).map(x=>[x.label,x.pct]));return `<div class="ci-section"><h3>Token Dağılımı · Current vs Final</h3><div style="overflow:auto"><table class="ci-table"><tr><th>Kategori</th><th>Şu an</th><th>Nihai</th></tr>${labels.map(l=>`<tr><td>${esc(l)}</td><td>${pct(cur[l])}</td><td>${pct(fin[l])}</td></tr>`).join('')}</table></div></div>`}
  function renderUnlock(r){const u=r.unlock_schedule||{};if(!u.available)return'<div class="ci-warn">Kamuya açık doğrulanmış unlock takvimi bulunamadı.</div>';return `<div class="ci-grid"><div class="ci-box"><div class="ci-label">Unlocked Supply</div><div class="ci-value">${pct(u.unlocked_pct)}</div></div><div class="ci-box"><div class="ci-label">Next Unlock</div><div class="ci-value">${esc((u.next_event||{}).date||'—')}</div></div><div class="ci-box"><div class="ci-label">Next Unlock / Float</div><div class="ci-value">${pct((u.next_event||{}).pct_float)}</div></div><div class="ci-box"><div class="ci-label">Next Unlock Tokens</div><div class="ci-value">${num((u.next_event||{}).tokens)}</div></div></div>${(u.events||[]).length?`<div style="overflow:auto"><table class="ci-table"><tr><th>Tarih</th><th>Tip</th><th>Kategori</th><th>Token</th><th>% Total</th><th>% Float</th><th>Değer</th></tr>${u.events.map(e=>`<tr><td>${esc(e.date||'—')}</td><td>${esc(e.type||'—')}</td><td>${esc(e.category||'—')}</td><td>${num(e.tokens)}</td><td>${pct(e.pct_total)}</td><td>${pct(e.pct_float)}</td><td>${money(e.value_usd)}</td></tr>`).join('')}</table></div>`:''}`}
  function renderInvestors(r){const f=r.funding||{},ii=r.investors||{};if(!f.available)return'<div class="ci-warn">Kamuya açık funding/backer verisi doğrulanamadı.</div>';const prof=Object.fromEntries((ii.items||[]).map(x=>[String(x.name||'').toLowerCase(),x]));return `<div class="ci-grid"><div class="ci-box"><div class="ci-label">Total Raised</div><div class="ci-value">${money(f.total_raised_usd)}</div></div><div class="ci-box"><div class="ci-label">Funding Round</div><div class="ci-value">${(f.rounds||[]).length}</div></div><div class="ci-box"><div class="ci-label">Doğrulanmış Yatırımcı</div><div class="ci-value">${(f.investors||[]).length}</div></div><div class="ci-box"><div class="ci-label">Research Güveni</div><div class="ci-value">${esc((r.evidence||{}).confidence||'—')}</div></div></div>${(f.rounds||[]).length?`<div style="overflow:auto"><table class="ci-table"><tr><th>Tarih</th><th>Tur</th><th>Tutar</th><th>Yatırımcılar</th></tr>${f.rounds.map(x=>`<tr><td>${esc(x.date||'—')}</td><td>${esc(x.round||'—')}</td><td>${money(x.amount_usd)}</td><td>${esc((x.investors||[]).join(', ')||'—')}</td></tr>`).join('')}</table></div>`:''}${(f.investors||[]).length?`<div class="ci-section"><h3>Yatırımcı Kalitesi / Diğer Yatırımları</h3><div style="overflow:auto"><table class="ci-table"><tr><th>Yatırımcı</th><th>Profil</th><th>Diğer yatırımlar</th><th>Neden önemli?</th></tr>${f.investors.map(n=>{const p=prof[String(n).toLowerCase()]||{};return `<tr><td><b>${esc(n)}</b></td><td>${esc(p.importance||'PUBLIC-RESEARCH')}${p.total_investments!=null?` · ${p.total_investments} yatırım`:''}</td><td>${esc((p.other_investments||[]).join(', ')||'—')}</td><td>${esc(p.why_it_matters||'Doğrulanmış yatırım turunda yer alıyor.')}</td></tr>`}).join('')}</table></div></div>`:''}`}
  function patch(d){const out=document.getElementById('coinIntelResult');if(!out)return;const r=d.public_research||{};const unlock=section(out,'Unlock Risk'),invest=section(out,'Backers / Investors');if(unlock)unlock.innerHTML=`<h3>Unlock Risk</h3>${renderUnlock(r)}${renderAllocation(r)}`;if(invest)invest.innerHTML=`<h3>Backers / Investors · Neden Önemli?</h3>${renderInvestors(r)}`}
  window.fetch=async function(input,init){const response=await originalFetch(input,init);try{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.includes('/api/public/coin-intelligence'))response.clone().json().then(d=>{if(d&&!d.error)setTimeout(()=>patch(d),90)}).catch(()=>{})}catch(e){}return response};
})();
