(function(){
  if(!location.pathname.endsWith('/agents/crypto_derivatives.html'))return;
  const fmtMoney=v=>{v=Number(v);if(!Number.isFinite(v))return'—';const a=Math.abs(v);return(v<0?'-':'')+'$'+(a>=1e9?(a/1e9).toFixed(2)+'B':a>=1e6?(a/1e6).toFixed(1)+'M':a>=1e3?(a/1e3).toFixed(1)+'K':a.toFixed(0))};
  const fmtStrike=v=>'$'+Math.round(Number(v)||0).toLocaleString('tr-TR');
  const dt=v=>new Date(v).toLocaleDateString('tr-TR',{day:'2-digit',month:'short',year:'2-digit'});
  function addStyle(){if(document.getElementById('mpProfileStyle'))return;const s=document.createElement('style');s.id='mpProfileStyle';s.textContent='.mp-profile{border-left:3px solid #d6b96f}.mp-row{display:grid;grid-template-columns:92px minmax(170px,1fr) 110px 90px;gap:10px;align-items:center;padding:9px 0;border-top:1px solid rgba(57,255,136,.10);font-size:10px}.mp-row:first-child{border-top:0}.mp-bar{height:10px;border-radius:999px;background:rgba(126,182,230,.12);overflow:hidden}.mp-fill{height:100%;background:linear-gradient(90deg,rgba(126,182,230,.45),rgba(126,182,230,.9));border-radius:999px}.mp-exp{font-weight:800}.mp-notional,.mp-pain{text-align:right}.mp-pain{color:#e7c878;font-weight:800}.mp-note{font-size:9px;color:var(--muted);line-height:1.6;margin-top:10px}@media(max-width:650px){.mp-row{grid-template-columns:76px 1fr 78px}.mp-notional{display:none}.mp-pain{font-size:9px}}';document.head.appendChild(s)}
  function card(p){const rows=(p.expiries||[]).slice(0,12);if(!rows.length)return'';const mx=Math.max(...rows.map(x=>Number(x.notional_usd)||0),1);return `<div id="maxPainProfileCard" class="card mp-profile"><h2>Max Pain · Vade Bazlı Loss Profile</h2><div class="note">Her vade için Deribit açık pozisyonundan ayrı max pain ve toplam notional.</div><div style="margin-top:10px">${rows.map(x=>`<div class="mp-row"><div class="mp-exp">${dt(x.expiry)}</div><div class="mp-bar" title="${fmtMoney(x.notional_usd)}"><div class="mp-fill" style="width:${Math.max(1,(Number(x.notional_usd)||0)/mx*100)}%"></div></div><div class="mp-notional">${fmtMoney(x.notional_usd)}</div><div class="mp-pain">${fmtStrike(x.max_pain)}</div></div>`).join('')}</div><div class="mp-note">Bar = notional OI, sağdaki değer = max pain. Notional = toplam BTC opsiyon OI × BTC index. Max pain teorik minimum toplu intrinsic payout seviyesidir; tek başına fiyat hedefi değildir.</div></div>`}
  async function load(){try{addStyle();const d=await(await fetch('../data/crypto_derivatives.json?t='+Date.now(),{cache:'no-store'})).json();const p=d.max_pain_profile;if(!p||p.error||!(p.expiries||[]).length)return;if(document.getElementById('maxPainProfileCard'))return;const holder=document.createElement('div');holder.innerHTML=card(p);const c=holder.firstElementChild;if(!c)return;const root=document.getElementById('content');if(!root)return;const cards=[...root.querySelectorAll('.card')];const chain=cards.find(x=>x.querySelector('h2')?.textContent.includes('Deribit Opsiyon Zinciri'));if(chain)chain.insertAdjacentElement('afterend',c);else root.appendChild(c)}catch(e){}}
  const obs=new MutationObserver(()=>load());obs.observe(document.documentElement,{childList:true,subtree:true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(load,500));else setTimeout(load,500);
})();