(function(){
  if(!location.pathname.endsWith('/agents/crypto.html'))return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const st=document.createElement('style');st.textContent=`
  .rot-legend{display:flex;flex-wrap:wrap;gap:8px;margin:8px 0 12px}.rot-legend span{font-size:9px;padding:3px 7px;border:1px solid rgba(57,255,136,.15);border-radius:999px}.rot-svg{width:100%;height:300px;border:1px solid rgba(57,255,136,.1);border-radius:10px;background:rgba(0,0,0,.14)}.net-svg{width:100%;height:260px;border:1px solid rgba(57,255,136,.1);border-radius:10px;background:rgba(0,0,0,.14)}.intel-meta{font-size:9px;line-height:1.6;color:var(--muted);margin-top:9px}.intel-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;flex-wrap:wrap}.tag-raw{font-size:8px;border:1px solid rgba(57,255,136,.3);color:#39ff88;border-radius:999px;padding:4px 7px}.tag-method{font-size:8px;border:1px solid rgba(255,207,92,.3);color:#ffcf5c;border-radius:999px;padding:4px 7px}.sector-table{width:100%;border-collapse:collapse;font-size:10px;margin-top:10px}.sector-table th,.sector-table td{padding:7px;border-bottom:1px solid rgba(57,255,136,.1);text-align:right}.sector-table th:first-child,.sector-table td:first-child{text-align:left}@media(max-width:650px){.rot-svg{height:240px}.net-svg{height:220px}.sector-table{font-size:9px}}
  `;document.head.appendChild(st);
  const COLORS=['#39ff88','#7eb6e6','#ffcf5c','#d6a5ff','#ff7f8a','#62e0d3','#f0a55b'];
  function lineChart(sectors){
    const entries=Object.entries(sectors||{}).filter(([,s])=>(s.points||[]).length>1);if(!entries.length)return'<div class="note">Sektör serisi üretilemedi.</div>';
    const W=900,H=300,p=36;const vals=entries.flatMap(([,s])=>s.points.map(x=>Number(x.value))).filter(Number.isFinite);let mn=Math.min(...vals),mx=Math.max(...vals);if(mx-mn<3){mx+=2;mn-=2}const dates=entries[0][1].points.map(x=>x.date);const x=i=>p+(W-2*p)*(i/Math.max(1,dates.length-1)),y=v=>H-p-(H-2*p)*((v-mn)/(mx-mn));
    let grid='';for(let i=0;i<5;i++){const v=mn+(mx-mn)*i/4,yy=y(v);grid+=`<line x1="${p}" y1="${yy}" x2="${W-p}" y2="${yy}" stroke="rgba(255,255,255,.08)"/><text x="5" y="${yy+3}" fill="#7d8b82" font-size="10">${v.toFixed(1)}</text>`}
    const lines=entries.map(([k,s],j)=>{const pts=(s.points||[]).map((q,i)=>`${x(i)},${y(Number(q.value))}`).join(' ');return `<polyline fill="none" stroke="${COLORS[j%COLORS.length]}" stroke-width="2.2" points="${pts}"/>`}).join('');
    const base=y(100);return `<svg class="rot-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}<line x1="${p}" y1="${base}" x2="${W-p}" y2="${base}" stroke="rgba(255,255,255,.26)" stroke-dasharray="4 4"/>${lines}<text x="${p}" y="${H-8}" fill="#7d8b82" font-size="10">${esc(dates[0]||'')}</text><text x="${W-p-80}" y="${H-8}" fill="#7d8b82" font-size="10">${esc(dates[dates.length-1]||'')}</text></svg>`}
  function netflowChart(points){
    points=(points||[]).slice(-45);if(!points.length)return'<div class="note">Güvenilir etiketli-cüzdan netflow serisi bu üretimde mevcut değil; proxy gösterilmiyor.</div>';
    const W=900,H=260,p=34;const vals=points.flatMap(r=>[Number(r.netflow_btc||0),Number(r.ma7_btc||0)]);const m=Math.max(1,...vals.map(Math.abs));const zero=H/2;const bw=(W-2*p)/points.length*.72;let bars='',ma='';points.forEach((r,i)=>{const xx=p+(W-2*p)*(i/points.length)+2, v=Number(r.netflow_btc||0),hh=Math.abs(v)/m*(H/2-p), yy=v>=0?zero-hh:zero;bars+=`<rect x="${xx}" y="${yy}" width="${bw}" height="${Math.max(1,hh)}" rx="1" fill="${v>=0?'#db747d':'#51c997'}" opacity=".9"/>`;const mv=Number(r.ma7_btc||0),my=zero-mv/m*(H/2-p);ma+=`${xx+bw/2},${my} `});return `<svg class="net-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="${p}" y1="${zero}" x2="${W-p}" y2="${zero}" stroke="rgba(255,255,255,.35)"/><text x="5" y="${zero+3}" fill="#7d8b82" font-size="10">0</text>${bars}<polyline fill="none" stroke="#e6d6a6" stroke-width="2" points="${ma.trim()}"/></svg>`}
  async function run(){try{const d=await(await fetch('../data/crypto.json?t='+Date.now(),{cache:'no-store'})).json();const content=document.getElementById('content');if(!content||document.getElementById('cryptoIntelExt'))return;const rot=d.sector_rotation||{},net=d.exchange_netflow||{};const sectors=rot.sectors||{};const names=Object.keys(sectors);const legend=names.map((k,i)=>`<span style="color:${COLORS[i%COLORS.length]}">● ${esc(k)} ${Number(sectors[k].return_pct||0)>=0?'+':''}${Number(sectors[k].return_pct||0).toFixed(1)}%</span>`).join('');const table=names.map(k=>`<tr><td>${esc(k)}</td><td>${Number(sectors[k].return_pct||0)>=0?'+':''}${Number(sectors[k].return_pct||0).toFixed(2)}%</td><td>${esc((sectors[k].constituents||[]).join(', '))}</td></tr>`).join('');const wrap=document.createElement('div');wrap.id='cryptoIntelExt';wrap.innerHTML=`<div class="card"><div class="intel-head"><div><h2>ALPHA Sector Rotation Index</h2><div class="intel-meta">Son ${rot.window_days||31} gün · 100 başlangıç bazlı relatif performans</div></div><span class="tag-method">ŞEFFAF EQUAL-WEIGHT BASKET</span></div><div class="rot-legend">${legend}</div>${lineChart(sectors)}<div style="overflow:auto"><table class="sector-table"><thead><tr><th>Sektör</th><th>Dönem</th><th>Temsilci coinler</th></tr></thead><tbody>${table}</tbody></table></div><div class="intel-meta">Kaynak: ${esc(rot.source||'Binance Spot')}. Metodoloji: ${esc(rot.method||'')}. Bu üçüncü taraf proprietary sektör endeksinin kopyası değildir; bileşenleri açık ALPHA endeksidir.</div></div><div class="card"><div class="intel-head"><div><h2>BTC Exchange Netflow</h2><div class="intel-meta">Borsa cüzdanlarına net giriş/çıkış · 7 günlük hareketli ortalama</div></div><span class="tag-raw">LABELLED-WALLET DATA</span></div>${netflowChart(net.points)}<div class="intel-meta">${net.ok?`Kaynak: ${esc(net.source||'—')}. Pozitif bar = borsalara net BTC girişi; negatif = net çıkış.`:esc(net.note||net.error||'Veri yok.')} ${esc(net.method||'')}</div></div>`;content.insertBefore(wrap,content.firstChild)}catch(e){}}
  setTimeout(run,800);
})();
