function tip(text){const s=String(text??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return `<span class="help-tip" tabindex="0" aria-label="${s}" data-tip="${s}">?</span>`}

(function(){
  if(!location.pathname.includes('crypto_derivatives.html')) return;
  const validNumber=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
  const money=v=>{if(!validNumber(v))return'—';v=Number(v);const a=Math.abs(v),s=v<0?'-':'';if(a>=1e9)return s+'$'+(a/1e9).toFixed(2)+'B';if(a>=1e6)return s+'$'+(a/1e6).toFixed(1)+'M';if(a>=1e3)return s+'$'+(a/1e3).toFixed(1)+'K';return s+'$'+a.toFixed(0)};
  const btc=v=>{if(!validNumber(v))return'—';v=Number(v);const a=Math.abs(v),s=v<0?'-':'';return s+(a>=1000?(a/1000).toFixed(2)+'K':a>=100?a.toFixed(0):a>=10?a.toFixed(1):a.toFixed(2))+' BTC'};
  const fund=v=>!validNumber(v)?'—':(Number(v)>=0?'+':'')+Number(v).toFixed(4)+'%';
  const ratio=v=>!validNumber(v)?'—':Number(v).toFixed(2);
  const css=`.flow15-card{border-left:3px solid #f3ba2f}.flow15-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.flow15-badge{font-size:9px;border:1px solid var(--green-dim);border-radius:999px;padding:4px 8px;color:var(--muted)}.flow15-section{font-size:11px;font-weight:800;color:#39ff88;margin:18px 0 4px;letter-spacing:.05em;text-transform:uppercase}.flow15-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:12px}.flow15-panel{border:1px solid var(--green-dim);border-radius:10px;padding:10px;overflow:hidden}.flow15-title{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:6px}.flow15-value{font-size:20px;font-weight:800;margin-bottom:8px}.flow15-canvas{width:100%;height:220px;display:block}.flow15-note{font-size:9px;line-height:1.55;color:var(--muted);margin-top:8px}.flow15-wait{height:220px;display:flex;align-items:center;justify-content:center;text-align:center;color:var(--muted);font-size:10px;border:1px dashed rgba(92,138,114,.25);border-radius:8px;padding:18px;box-sizing:border-box}@media(max-width:900px){.flow15-grid{grid-template-columns:1fr}}@media(max-width:700px){.flow15-canvas,.flow15-wait{height:190px}}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  function fmtTime(v){try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(e){return''}}
  function lineChart(canvas,rows,key,formatter,zero=false){if(!canvas)return;const s=rows.filter(r=>validNumber(r[key]));if(s.length<2)return;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,W=Math.max(300,rect.width),H=Math.max(180,rect.height);canvas.width=W*dpr;canvas.height=H*dpr;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,W,H);const p={l:64,r:12,t:12,b:28},pw=W-p.l-p.r,ph=H-p.t-p.b,vals=s.map(r=>Number(r[key]));let min=Math.min(...vals),max=Math.max(...vals);if(zero){min=Math.min(min,0);max=Math.max(max,0)}if(min===max){const b=Math.abs(min||1)*.01;min-=b;max+=b}else if(!zero){const b=(max-min)*.12;min-=b;max+=b}const x=i=>p.l+pw*i/(s.length-1),y=v=>p.t+ph*(1-(v-min)/(max-min));c.font='9px IBM Plex Mono, monospace';for(let i=0;i<=4;i++){const yy=p.t+ph*i/4,val=max-(max-min)*i/4;c.strokeStyle='rgba(92,138,114,.14)';c.beginPath();c.moveTo(p.l,yy);c.lineTo(W-p.r,yy);c.stroke();c.fillStyle='#5c8a72';c.textAlign='right';c.fillText(formatter(val),p.l-6,yy+3)}if(zero&&min<0&&max>0){const yy=y(0);c.strokeStyle='rgba(255,207,92,.35)';c.beginPath();c.moveTo(p.l,yy);c.lineTo(W-p.r,yy);c.stroke()}c.strokeStyle='#39ff88';c.lineWidth=2;c.beginPath();s.forEach((r,i)=>{i?c.lineTo(x(i),y(Number(r[key]))):c.moveTo(x(i),y(Number(r[key]))) });c.stroke();c.fillStyle='#5c8a72';c.textAlign='center';[0,.25,.5,.75,1].forEach(q=>{const i=Math.min(s.length-1,Math.round((s.length-1)*q));c.fillText(fmtTime(s[i].ts),x(i),H-8)})}
  const series=(rows,key)=>rows.filter(r=>validNumber(r[key]));
  const change=(s,key)=>s.length>=2&&Number(s[0][key])!==0?(Number(s[s.length-1][key])/Number(s[0][key])-1)*100:null;
  const total=(s,key)=>s.reduce((a,r)=>a+(validNumber(r[key])?Number(r[key]):0),0);
  const panel=(title,value,id,s,wait,note)=>`<div class="flow15-panel"><div class="flow15-title">${title}</div><div class="flow15-value">${value}</div>${s.length>=2?`<canvas id="${id}" class="flow15-canvas"></canvas>`:`<div class="flow15-wait">${wait}</div>`}<div class="flow15-note">${note}</div></div>`;
  let started=false;
  async function inject(){const content=document.getElementById('content');if(!content||document.getElementById('flow15Card')||started)return;started=true;let data;try{data=await(await fetch('../data/crypto_flow_history.json?t='+Date.now())).json()}catch(e){started=false;return}if(data.venue!=='Binance'){started=false;return}const rows=(data.points||[]).slice(-144);if(!rows.length){started=false;return}
    const spot=series(rows,'spot_cvd_cumulative_btc'),perp=series(rows,'perp_cvd_cumulative_btc'),aoi=series(rows,'aggregate_oi_usd'),af=series(rows,'aggregate_oi_weighted_funding_pct'),aliq=series(rows,'aggregate_liquidations_10m_usd'),boi=series(rows,'binance_oi_usd'),bf=series(rows,'binance_funding_pct'),bls=series(rows,'binance_long_short_ratio'),bliq=series(rows,'binance_liquidations_10m_usd');
    const last=s=>s[s.length-1]||{};const aoiCh=change(aoi,'aggregate_oi_usd'),boiCh=change(boi,'binance_oi_usd');
    const card=document.createElement('div');card.id='flow15Card';card.className='card flow15-card';card.innerHTML=`<div class="flow15-head"><div><h2>Coinalyze · BTC 10dk Akış ve Kaldıraç Grafikleri</h2><div class="note">Son 24 saat · 10dk · Tüm borsalar + Binance</div></div><div class="flow15-badge">${data.aggregate_exchange_count||'—'} borsa · ${rows.length} nokta</div></div><div class="flow15-section">Piyasa Geneli</div><div class="flow15-grid">${panel('Tüm Borsalar BTC Perp OI',`${money(last(aoi).aggregate_oi_usd)} ${aoiCh==null?'':`<span style="font-size:11px;color:${aoiCh>=0?'#39ff88':'#ff5c5c'}">${aoiCh>=0?'+':''}${aoiCh.toFixed(2)}% / 24s</span>`}`,'aggOiCanvas',aoi,'Aggregate OI bekleniyor.','Her borsadan bir ana BTC perpetual; USD OI toplamı.')}${panel('Tüm Borsalar OI-Ağırlıklı Funding',fund(last(af).aggregate_oi_weighted_funding_pct),'aggFundingCanvas',af,'Aggregate funding bekleniyor.','Her borsanın funding oranı kendi OI büyüklüğü ile ağırlıklandırılır.')}${panel('Tüm Borsalar Liquidation · 10dk',money(last(aliq).aggregate_liquidations_10m_usd)+` <span style="font-size:11px">24s toplam ${money(total(aliq,'aggregate_liquidations_10m_usd'))}</span>`,'aggLiqCanvas',aliq,'Liquidation history bekleniyor.','Her nokta o 10 dakikadaki long + short liquidation toplamı; üstte 24s toplam ayrıca gösterilir.')}</div><div class="flow15-section">Binance</div><div class="flow15-grid">${panel('Binance Spot BTC CVD',btc(last(spot).spot_cvd_cumulative_btc),'spotCvd15Canvas',spot,'Spot CVD bekleniyor.','Spot buy volume − sell volume; kümülatif BTC CVD.')}${panel('Binance Futures BTC CVD',btc(last(perp).perp_cvd_cumulative_btc),'perpCvd15Canvas',perp,'Futures CVD bekleniyor.','BTC perpetual buy volume − sell volume; kümülatif Futures CVD.')}${panel('Binance BTC Perp OI',`${money(last(boi).binance_oi_usd)} ${boiCh==null?'':`<span style="font-size:11px;color:${boiCh>=0?'#39ff88':'#ff5c5c'}">${boiCh>=0?'+':''}${boiCh.toFixed(2)}% / 24s</span>`}`,'binanceOiCanvas',boi,'Binance OI bekleniyor.','Binance BTC perpetual OI, USD.')}${panel('Binance Funding Rate',fund(last(bf).binance_funding_pct),'binanceFundingCanvas',bf,'Binance funding bekleniyor.','Pozitif: longlar shortlara ödeme yapar; negatif: shortlar longlara.')}${panel('Binance Long / Short',ratio(last(bls).binance_long_short_ratio),'binanceLsCanvas',bls,'Binance long/short bekleniyor.','1 üzeri long ağırlığı, 1 altı short ağırlığı.')}${panel('Binance Liquidation · 10dk',money(last(bliq).binance_liquidations_10m_usd)+` <span style="font-size:11px">24s toplam ${money(total(bliq,'binance_liquidations_10m_usd'))}</span>`,'binanceLiqCanvas',bliq,'Binance liquidation bekleniyor.','Her nokta o 10 dakikadaki Binance long + short tasfiye toplamı.')}</div>`;content.insertBefore(card,content.firstChild);
    const draw=()=>{lineChart(document.getElementById('aggOiCanvas'),rows,'aggregate_oi_usd',money);lineChart(document.getElementById('aggFundingCanvas'),rows,'aggregate_oi_weighted_funding_pct',fund,true);lineChart(document.getElementById('aggLiqCanvas'),rows,'aggregate_liquidations_10m_usd',money);lineChart(document.getElementById('spotCvd15Canvas'),rows,'spot_cvd_cumulative_btc',btc,true);lineChart(document.getElementById('perpCvd15Canvas'),rows,'perp_cvd_cumulative_btc',btc,true);lineChart(document.getElementById('binanceOiCanvas'),rows,'binance_oi_usd',money);lineChart(document.getElementById('binanceFundingCanvas'),rows,'binance_funding_pct',fund,true);lineChart(document.getElementById('binanceLsCanvas'),rows,'binance_long_short_ratio',ratio);lineChart(document.getElementById('binanceLiqCanvas'),rows,'binance_liquidations_10m_usd',money)};requestAnimationFrame(draw);window.addEventListener('resize',draw,{passive:true});
  }
  const obs=new MutationObserver(()=>{const c=document.getElementById('content');if(c&&c.children.length){inject();obs.disconnect()}});obs.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState!=='loading')setTimeout(inject,300);else document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,300));
})();

(function(){
  if(!location.pathname.includes('equities.html')) return;
  const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const style=document.createElement('style');style.textContent=`.bist-agent-comment{margin:12px 14px 14px;padding:13px;border:1px solid rgba(57,255,136,.25);border-radius:10px;background:rgba(8,22,14,.45)}.bist-agent-title{font-size:10px;color:#39ff88;font-weight:800;letter-spacing:.08em;margin-bottom:8px}.bist-agent-head{font-size:11px;font-weight:800;margin-bottom:7px}.bist-agent-text{font-size:10px;line-height:1.7;color:var(--text)}.bist-agent-risk{font-size:9px;line-height:1.6;color:#ffcf5c;margin-top:7px}`;document.head.appendChild(style);
  let running=false;
  async function addComments(){if(running)return;running=true;let data;try{data=await(await fetch('../data/equities.json?t='+Date.now())).json()}catch(e){running=false;return}for(const x of data.bist_fundamentals||[]){const card=document.getElementById('bist-'+x.symbol);if(!card||card.querySelector('.bist-agent-comment'))continue;const i=x.interpretation||{};const box=document.createElement('div');box.className='bist-agent-comment';box.innerHTML=`<div class="bist-agent-title">AJAN YORUMU</div><div class="bist-agent-head">${esc(i.headline||'Doğrulanmış temel yorum henüz yok.')}</div><div class="bist-agent-text">${esc(i.summary||'Yeterli doğrulanmış veri oluşunca burada bilanço ve kârlılık yorumu gösterilecek.')}</div>${(i.risks||[]).map(r=>`<div class="bist-agent-risk">⚠ ${esc(r)}</div>`).join('')}`;card.appendChild(box)}running=false}
  const obs=new MutationObserver(()=>{if(document.querySelector('.bist-fund-card')){addComments();obs.disconnect()}});obs.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState!=='loading')setTimeout(addComments,600);else document.addEventListener('DOMContentLoaded',()=>setTimeout(addComments,600));
})();

(function(){
  if(!location.pathname.includes('macro.html')) return;
  const style=document.createElement('style');style.textContent=`.netliq-card{border-left:3px solid #d7b96f}.netliq-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px}.netliq-box{border:1px solid var(--green-dim);border-radius:10px;padding:12px}.netliq-label{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}.netliq-value{font-size:26px;font-weight:800;margin-top:5px}.netliq-status{font-size:10px;font-weight:800;margin-top:5px}.netliq-note{font-size:9px;color:var(--muted);line-height:1.6;margin-top:10px}@media(max-width:640px){.netliq-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  let started=false;
  async function injectNetLiquidity(){const content=document.getElementById('content');if(!content||document.getElementById('netLiquidity3wCard')||started)return;started=true;let d;try{d=await(await fetch('../data/macro.json?t='+Date.now())).json()}catch(e){started=false;return}const n=d?.liquidity_plumbing?.net_liquidity_proxy;if(!n){started=false;return}const delta=Number(n.change_3w??n.change),level=Number(n.value);const deltaOk=Number.isFinite(delta),levelOk=Number.isFinite(level);const status=!deltaOk?'VERİ YOK':delta>50?'DESTEKLEYİCİ':delta<-50?'RISK-OFF':'NÖTR / KARIŞIK';const statusColor=!deltaOk?'var(--muted)':delta>50?'#39ff88':delta<-50?'#ff5c5c':'#ffcf5c';const fmtB=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(0)} $B`:'—';const card=document.createElement('div');card.id='netLiquidity3wCard';card.className='card netliq-card';card.innerHTML=`<h2>Net Likidite (3-Hafta Δ) ${tip('Fed bilançosu − TGA − ON RRP. Değişim, tüm bileşenler yaklaşık 21 takvim günü öncesine hizalanarak hesaplanır.')}</h2><div class="netliq-grid"><div class="netliq-box"><div class="netliq-label">3 Haftalık Değişim</div><div class="netliq-value" style="color:${statusColor}">${fmtB(delta)}</div><div class="netliq-status" style="color:${statusColor}">${status}</div></div><div class="netliq-box"><div class="netliq-label">Net Likidite Seviyesi</div><div class="netliq-value">${levelOk?'$'+(level/1000).toFixed(2)+'T':'—'}</div><div class="netliq-status">Fed − TGA − RRP</div></div></div><div class="netliq-note">WinCAlgo yaklaşımına yaklaştırılmış 3-hafta Δ görünümü. Bu mekanik bir likidite proxy'sidir; tek başına QE veya al/sat sinyali değildir.</div>`;content.insertBefore(card,content.firstChild)}
  const obs=new MutationObserver(()=>{const c=document.getElementById('content');if(c&&c.children.length){injectNetLiquidity();obs.disconnect()}});obs.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState!=='loading')setTimeout(injectNetLiquidity,500);else document.addEventListener('DOMContentLoaded',()=>setTimeout(injectNetLiquidity,500));
})();

(function(){const s=document.createElement('script');s.src='../global.js';s.defer=true;document.head.appendChild(s)})();